### ISSUE TITLE
Adjusting the weights for simplicity

### ISSUE THREAD

**Issue by andreaNCCEH** [timbender-ncceh/ce_assessment#3]
- [x] [TODO: normalize to zero -1 on the negative side] 

- [x] [TODO: normalize on a scale from -1:-10] 

- [x] [TODO: consider setting a max composite weight limit]

**Comment by timbender-ncceh** [comment]
@andreaNCCEH adjusting weights for simplicity refers to these values (below) having 7 decimal points, correct? 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/4e524ab5-8bda-4c83-9d49-01fb4543e6e8)

**Comment by andreaNCCEH** [comment]
@timbender-ncceh Correct! We want whole number positive integers if possible, instead of negatives and decimals.

**Comment by timbender-ncceh** [comment]
@andreaNCCEH I setup a max_score variable input for the individual client composite score in the model, but I've currently set it at something like 10,000 so that it's not in use.  I think the highest possible score is 18 and we're seeing people score that much.  
@andreaNCCEH I've complete all other items.
